using System;

namespace SC.AgentDeployer.Client.Models;

[Flags]
public enum SCM_ACCESS : uint
{
	STANDARD_RIGHTS_REQUIRED = 0xF0000u,
	SC_MANAGER_CONNECT = 1u,
	SC_MANAGER_CREATE_SERVICE = 2u,
	SC_MANAGER_ENUMERATE_SERVICE = 4u,
	SC_MANAGER_LOCK = 8u,
	SC_MANAGER_QUERY_LOCK_STATUS = 0x10u,
	SC_MANAGER_MODIFY_BOOT_CONFIG = 0x20u,
	SC_MANAGER_ALL_ACCESS = 0xF003Fu
}
