using System;

namespace SC.AgentDeployer.Client.Models;

[Flags]
public enum SERVICE_ACCESS : uint
{
	STANDARD_RIGHTS_REQUIRED = 0xF0000u,
	SERVICE_QUERY_CONFIG = 1u,
	SERVICE_CHANGE_CONFIG = 2u,
	SERVICE_QUERY_STATUS = 4u,
	SERVICE_ENUMERATE_DEPENDENTS = 8u,
	SERVICE_START = 0x10u,
	SERVICE_STOP = 0x20u,
	SERVICE_PAUSE_CONTINUE = 0x40u,
	SERVICE_INTERROGATE = 0x80u,
	SERVICE_USER_DEFINED_CONTROL = 0x100u,
	SERVICE_ALL_ACCESS = 0xF01FFu
}
