using System;

namespace SC.AgentDeployer.Client.Models;

[Flags]
public enum SERVICE_TYPES
{
	SERVICE_KERNEL_DRIVER = 1,
	SERVICE_FILE_SYSTEM_DRIVER = 2,
	SERVICE_WIN32_OWN_PROCESS = 0x10,
	SERVICE_WIN32_SHARE_PROCESS = 0x20,
	SERVICE_INTERACTIVE_PROCESS = 0x100
}
